"""Update foreign key relationships and resolve issues

Revision ID: d26c4d1e26f8
Revises: 6b7afacef93c
Create Date: 2025-01-14 23:57:01.098883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd26c4d1e26f8'
down_revision = '6b7afacef93c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_purchased')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_purchased', sa.DATETIME(), nullable=False))
        batch_op.drop_column('date')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
